### ISSUE TITLE
Config files for Mac

### ISSUE THREAD

**Issue by OttoTheCat** [jmc2obj/j-mc-2-obj#154] opened 2021-04-06 04:18 UTC
Reading materials file...
ERROR: Error reading configuration file:
java.lang.Exception: Cannot open configuration file conf/default.mtl
	at org.jmc.Materials.readConfig(Materials.java:42)
	at org.jmc.Materials.initialize(Materials.java:95)
	at org.jmc.Main.runGUI(Main.java:68)
	at org.jmc.Main.main(Main.java:46)

I cannot load worlds because of this config file problem.

**Comment by mmdanggg2** [comment] 2021-04-06 19:01
Duplicate of #127 - make sure you have write permission for the folder the .jar is in.

**Closed by mmdanggg2** 2021-04-06 19:01 UTC
