### ISSUE TITLE
Cannot open / load / do anything....

### ISSUE THREAD

**Issue by namanyt** [jmc2obj/j-mc-2-obj#143] opened 2020-12-27 03:57 UTC
hello,
I'm using Java 8 and trying to open jMc2OJB on my Mac...
this is the following error I got -->
```
ERROR: Error reading configuration file:
java.lang.Exception: Cannot open configuration file conf/default.mtl
	at org.jmc.Materials.readConfig(Materials.java:41)
	at org.jmc.Materials.initialize(Materials.java:88)
	at org.jmc.Main.runGUI(Main.java:68)
	at org.jmc.Main.main(Main.java:46)
```

**Comment by Rikopara** [comment] 2021-01-15 17:57
Agree, have same issue on Windows.

**Comment by Rikopara** [comment] 2021-01-15 18:10
Ok, I fixed it by moving .jar file to Downloads folder on C:\. 
At my computer, Documents and Desktop folders were on Onedrive so they won't work either.

**Comment by mmdanggg2** [comment] 2021-01-16 17:02
Duplicate of #127 - seems to be lack of write permissions in the folder where the .jar is.

**Closed by mmdanggg2** 2021-01-16 17:02 UTC
